#!/bin/sh

HOME=/home/mosluce
APP_NAME=$1

if [ -z "$1" ]; then
  echo "name required"
  exit 1
fi

docker rm -f $APP_NAME

rm -rf $HOME/repos/$APP_NAME.git
rm -rf $HOME/apps/$APP_NAME

rm -f $HOME/server-tools/configs/sites-enabled/$APP_NAME.conf
